sudo: false
language: go

before_install:
    - echo ${TRAVIS_BUILD_DIR}
    - ls ${TRAVIS_BUILD_DIR}

script:
    - cd ${TRAVIS_BUILD_DIR}/wpwithin/core && go test
    # - cd ${TRAVIS_BUILD_DIR}/wpwithin && go test
    - cd ${TRAVIS_BUILD_DIR}/wpwithin/configuration && go test
