// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
	"github.com/wptechinnovation/wpw-sdk-go/wpwithin/rpc/wpthrift/gen-go/wpthrift_types"
        "github.com/wptechinnovation/wpw-sdk-go/wpwithin/rpc/wpthrift/gen-go/wpthrift"
)

var _ = wpthrift_types.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void setup(string name, string description, string interfaceAddr)")
  fmt.Fprintln(os.Stderr, "  void addService(Service svc)")
  fmt.Fprintln(os.Stderr, "  void removeService(Service svc)")
  fmt.Fprintln(os.Stderr, "  void initConsumer(string scheme, string hostname, i32 port, string urlPrefix, string clientID, HCECard hceCard,  pspConfig)")
  fmt.Fprintln(os.Stderr, "  void initProducer( pspConfig)")
  fmt.Fprintln(os.Stderr, "  Device getDevice()")
  fmt.Fprintln(os.Stderr, "  void startServiceBroadcast(i32 timeoutMillis)")
  fmt.Fprintln(os.Stderr, "  void stopServiceBroadcast()")
  fmt.Fprintln(os.Stderr, "   deviceDiscovery(i32 timeoutMillis)")
  fmt.Fprintln(os.Stderr, "  ServiceMessage searchForDevice(i32 timeoutMillis, string deviceName)")
  fmt.Fprintln(os.Stderr, "   requestServices()")
  fmt.Fprintln(os.Stderr, "   getServicePrices(i32 serviceId)")
  fmt.Fprintln(os.Stderr, "  TotalPriceResponse selectService(i32 serviceId, i32 numberOfUnits, i32 priceId)")
  fmt.Fprintln(os.Stderr, "  PaymentResponse makePayment(TotalPriceResponse request)")
  fmt.Fprintln(os.Stderr, "  ServiceDeliveryToken beginServiceDelivery(i32 serviceID, ServiceDeliveryToken serviceDeliveryToken, i32 unitsToSupply)")
  fmt.Fprintln(os.Stderr, "  ServiceDeliveryToken endServiceDelivery(i32 serviceID, ServiceDeliveryToken serviceDeliveryToken, i32 unitsReceived)")
  fmt.Fprintln(os.Stderr, "  void CloseRPCAgent()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := wpthrift.NewWPWithinClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "setup":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "Setup requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.Setup(value0, value1, value2))
    fmt.Print("\n")
    break
  case "addService":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AddService requires 1 args")
      flag.Usage()
    }
    arg46 := flag.Arg(1)
    mbTrans47 := thrift.NewTMemoryBufferLen(len(arg46))
    defer mbTrans47.Close()
    _, err48 := mbTrans47.WriteString(arg46)
    if err48 != nil {
      Usage()
      return
    }
    factory49 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt50 := factory49.GetProtocol(mbTrans47)
    argvalue0 := wpthrift_types.NewService()
    err51 := argvalue0.Read(jsProt50)
    if err51 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.AddService(value0))
    fmt.Print("\n")
    break
  case "removeService":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RemoveService requires 1 args")
      flag.Usage()
    }
    arg52 := flag.Arg(1)
    mbTrans53 := thrift.NewTMemoryBufferLen(len(arg52))
    defer mbTrans53.Close()
    _, err54 := mbTrans53.WriteString(arg52)
    if err54 != nil {
      Usage()
      return
    }
    factory55 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt56 := factory55.GetProtocol(mbTrans53)
    argvalue0 := wpthrift_types.NewService()
    err57 := argvalue0.Read(jsProt56)
    if err57 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.RemoveService(value0))
    fmt.Print("\n")
    break
  case "initConsumer":
    if flag.NArg() - 1 != 7 {
      fmt.Fprintln(os.Stderr, "InitConsumer requires 7 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err60 := (strconv.Atoi(flag.Arg(3)))
    if err60 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    argvalue4 := flag.Arg(5)
    value4 := argvalue4
    arg63 := flag.Arg(6)
    mbTrans64 := thrift.NewTMemoryBufferLen(len(arg63))
    defer mbTrans64.Close()
    _, err65 := mbTrans64.WriteString(arg63)
    if err65 != nil {
      Usage()
      return
    }
    factory66 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt67 := factory66.GetProtocol(mbTrans64)
    argvalue5 := wpthrift_types.NewHCECard()
    err68 := argvalue5.Read(jsProt67)
    if err68 != nil {
      Usage()
      return
    }
    value5 := argvalue5
    arg69 := flag.Arg(7)
    mbTrans70 := thrift.NewTMemoryBufferLen(len(arg69))
    defer mbTrans70.Close()
    _, err71 := mbTrans70.WriteString(arg69)
    if err71 != nil { 
      Usage()
      return
    }
    factory72 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt73 := factory72.GetProtocol(mbTrans70)
    containerStruct6 := wpthrift.NewWPWithinInitConsumerArgs()
    err74 := containerStruct6.ReadField7(jsProt73)
    if err74 != nil {
      Usage()
      return
    }
    argvalue6 := containerStruct6.PspConfig
    value6 := argvalue6
    fmt.Print(client.InitConsumer(value0, value1, value2, value3, value4, value5, value6))
    fmt.Print("\n")
    break
  case "initProducer":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "InitProducer requires 1 args")
      flag.Usage()
    }
    arg75 := flag.Arg(1)
    mbTrans76 := thrift.NewTMemoryBufferLen(len(arg75))
    defer mbTrans76.Close()
    _, err77 := mbTrans76.WriteString(arg75)
    if err77 != nil { 
      Usage()
      return
    }
    factory78 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt79 := factory78.GetProtocol(mbTrans76)
    containerStruct0 := wpthrift.NewWPWithinInitProducerArgs()
    err80 := containerStruct0.ReadField1(jsProt79)
    if err80 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.PspConfig
    value0 := argvalue0
    fmt.Print(client.InitProducer(value0))
    fmt.Print("\n")
    break
  case "getDevice":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetDevice requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetDevice())
    fmt.Print("\n")
    break
  case "startServiceBroadcast":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "StartServiceBroadcast requires 1 args")
      flag.Usage()
    }
    tmp0, err81 := (strconv.Atoi(flag.Arg(1)))
    if err81 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.StartServiceBroadcast(value0))
    fmt.Print("\n")
    break
  case "stopServiceBroadcast":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "StopServiceBroadcast requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.StopServiceBroadcast())
    fmt.Print("\n")
    break
  case "deviceDiscovery":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DeviceDiscovery requires 1 args")
      flag.Usage()
    }
    tmp0, err82 := (strconv.Atoi(flag.Arg(1)))
    if err82 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.DeviceDiscovery(value0))
    fmt.Print("\n")
    break
  case "searchForDevice":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SearchForDevice requires 2 args")
      flag.Usage()
    }
    tmp0, err83 := (strconv.Atoi(flag.Arg(1)))
    if err83 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SearchForDevice(value0, value1))
    fmt.Print("\n")
    break
  case "requestServices":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "RequestServices requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.RequestServices())
    fmt.Print("\n")
    break
  case "getServicePrices":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetServicePrices requires 1 args")
      flag.Usage()
    }
    tmp0, err85 := (strconv.Atoi(flag.Arg(1)))
    if err85 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetServicePrices(value0))
    fmt.Print("\n")
    break
  case "selectService":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SelectService requires 3 args")
      flag.Usage()
    }
    tmp0, err86 := (strconv.Atoi(flag.Arg(1)))
    if err86 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    tmp1, err87 := (strconv.Atoi(flag.Arg(2)))
    if err87 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err88 := (strconv.Atoi(flag.Arg(3)))
    if err88 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.SelectService(value0, value1, value2))
    fmt.Print("\n")
    break
  case "makePayment":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "MakePayment requires 1 args")
      flag.Usage()
    }
    arg89 := flag.Arg(1)
    mbTrans90 := thrift.NewTMemoryBufferLen(len(arg89))
    defer mbTrans90.Close()
    _, err91 := mbTrans90.WriteString(arg89)
    if err91 != nil {
      Usage()
      return
    }
    factory92 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt93 := factory92.GetProtocol(mbTrans90)
    argvalue0 := wpthrift_types.NewTotalPriceResponse()
    err94 := argvalue0.Read(jsProt93)
    if err94 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.MakePayment(value0))
    fmt.Print("\n")
    break
  case "beginServiceDelivery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "BeginServiceDelivery requires 3 args")
      flag.Usage()
    }
    tmp0, err95 := (strconv.Atoi(flag.Arg(1)))
    if err95 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    arg96 := flag.Arg(2)
    mbTrans97 := thrift.NewTMemoryBufferLen(len(arg96))
    defer mbTrans97.Close()
    _, err98 := mbTrans97.WriteString(arg96)
    if err98 != nil {
      Usage()
      return
    }
    factory99 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt100 := factory99.GetProtocol(mbTrans97)
    argvalue1 := wpthrift_types.NewServiceDeliveryToken()
    err101 := argvalue1.Read(jsProt100)
    if err101 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err102 := (strconv.Atoi(flag.Arg(3)))
    if err102 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.BeginServiceDelivery(value0, value1, value2))
    fmt.Print("\n")
    break
  case "endServiceDelivery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "EndServiceDelivery requires 3 args")
      flag.Usage()
    }
    tmp0, err103 := (strconv.Atoi(flag.Arg(1)))
    if err103 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    arg104 := flag.Arg(2)
    mbTrans105 := thrift.NewTMemoryBufferLen(len(arg104))
    defer mbTrans105.Close()
    _, err106 := mbTrans105.WriteString(arg104)
    if err106 != nil {
      Usage()
      return
    }
    factory107 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt108 := factory107.GetProtocol(mbTrans105)
    argvalue1 := wpthrift_types.NewServiceDeliveryToken()
    err109 := argvalue1.Read(jsProt108)
    if err109 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err110 := (strconv.Atoi(flag.Arg(3)))
    if err110 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.EndServiceDelivery(value0, value1, value2))
    fmt.Print("\n")
    break
  case "CloseRPCAgent":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "CloseRPCAgent requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.CloseRPCAgent())
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
