// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
	"github.com/WPTechInnovation/wpw-sdk-go/wpwithin/rpc/wpthrift/gen-go/wpthrift_types"
        "github.com/WPTechInnovation/wpw-sdk-go/wpwithin/rpc/wpthrift/gen-go/wpthrift"
)

var _ = wpthrift_types.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  void setup(string name, string description)")
  fmt.Fprintln(os.Stderr, "  void addService(Service svc)")
  fmt.Fprintln(os.Stderr, "  void removeService(Service svc)")
  fmt.Fprintln(os.Stderr, "  void initConsumer(string scheme, string hostname, i32 port, string urlPrefix, string clientID, HCECard hceCard,  pspConfig)")
  fmt.Fprintln(os.Stderr, "  void initProducer( pspConfig)")
  fmt.Fprintln(os.Stderr, "  Device getDevice()")
  fmt.Fprintln(os.Stderr, "  void startServiceBroadcast(i32 timeoutMillis)")
  fmt.Fprintln(os.Stderr, "  void stopServiceBroadcast()")
  fmt.Fprintln(os.Stderr, "   deviceDiscovery(i32 timeoutMillis)")
  fmt.Fprintln(os.Stderr, "  ServiceMessage searchForDevice(i32 timeoutMillis, string deviceName)")
  fmt.Fprintln(os.Stderr, "   requestServices()")
  fmt.Fprintln(os.Stderr, "   getServicePrices(i32 serviceId)")
  fmt.Fprintln(os.Stderr, "  TotalPriceResponse selectService(i32 serviceId, i32 numberOfUnits, i32 priceId)")
  fmt.Fprintln(os.Stderr, "  PaymentResponse makePayment(TotalPriceResponse request)")
  fmt.Fprintln(os.Stderr, "  ServiceDeliveryToken beginServiceDelivery(i32 serviceID, ServiceDeliveryToken serviceDeliveryToken, i32 unitsToSupply)")
  fmt.Fprintln(os.Stderr, "  ServiceDeliveryToken endServiceDelivery(i32 serviceID, ServiceDeliveryToken serviceDeliveryToken, i32 unitsReceived)")
  fmt.Fprintln(os.Stderr, "  void CloseRPCAgent()")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := wpthrift.NewWPWithinClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "setup":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Setup requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Setup(value0, value1))
    fmt.Print("\n")
    break
  case "addService":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "AddService requires 1 args")
      flag.Usage()
    }
    arg45 := flag.Arg(1)
    mbTrans46 := thrift.NewTMemoryBufferLen(len(arg45))
    defer mbTrans46.Close()
    _, err47 := mbTrans46.WriteString(arg45)
    if err47 != nil {
      Usage()
      return
    }
    factory48 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt49 := factory48.GetProtocol(mbTrans46)
    argvalue0 := wpthrift_types.NewService()
    err50 := argvalue0.Read(jsProt49)
    if err50 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.AddService(value0))
    fmt.Print("\n")
    break
  case "removeService":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RemoveService requires 1 args")
      flag.Usage()
    }
    arg51 := flag.Arg(1)
    mbTrans52 := thrift.NewTMemoryBufferLen(len(arg51))
    defer mbTrans52.Close()
    _, err53 := mbTrans52.WriteString(arg51)
    if err53 != nil {
      Usage()
      return
    }
    factory54 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt55 := factory54.GetProtocol(mbTrans52)
    argvalue0 := wpthrift_types.NewService()
    err56 := argvalue0.Read(jsProt55)
    if err56 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.RemoveService(value0))
    fmt.Print("\n")
    break
  case "initConsumer":
    if flag.NArg() - 1 != 7 {
      fmt.Fprintln(os.Stderr, "InitConsumer requires 7 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    tmp2, err59 := (strconv.Atoi(flag.Arg(3)))
    if err59 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    argvalue4 := flag.Arg(5)
    value4 := argvalue4
    arg62 := flag.Arg(6)
    mbTrans63 := thrift.NewTMemoryBufferLen(len(arg62))
    defer mbTrans63.Close()
    _, err64 := mbTrans63.WriteString(arg62)
    if err64 != nil {
      Usage()
      return
    }
    factory65 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt66 := factory65.GetProtocol(mbTrans63)
    argvalue5 := wpthrift_types.NewHCECard()
    err67 := argvalue5.Read(jsProt66)
    if err67 != nil {
      Usage()
      return
    }
    value5 := argvalue5
    arg68 := flag.Arg(7)
    mbTrans69 := thrift.NewTMemoryBufferLen(len(arg68))
    defer mbTrans69.Close()
    _, err70 := mbTrans69.WriteString(arg68)
    if err70 != nil { 
      Usage()
      return
    }
    factory71 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt72 := factory71.GetProtocol(mbTrans69)
    containerStruct6 := wpthrift.NewWPWithinInitConsumerArgs()
    err73 := containerStruct6.ReadField7(jsProt72)
    if err73 != nil {
      Usage()
      return
    }
    argvalue6 := containerStruct6.PspConfig
    value6 := argvalue6
    fmt.Print(client.InitConsumer(value0, value1, value2, value3, value4, value5, value6))
    fmt.Print("\n")
    break
  case "initProducer":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "InitProducer requires 1 args")
      flag.Usage()
    }
    arg74 := flag.Arg(1)
    mbTrans75 := thrift.NewTMemoryBufferLen(len(arg74))
    defer mbTrans75.Close()
    _, err76 := mbTrans75.WriteString(arg74)
    if err76 != nil { 
      Usage()
      return
    }
    factory77 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt78 := factory77.GetProtocol(mbTrans75)
    containerStruct0 := wpthrift.NewWPWithinInitProducerArgs()
    err79 := containerStruct0.ReadField1(jsProt78)
    if err79 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.PspConfig
    value0 := argvalue0
    fmt.Print(client.InitProducer(value0))
    fmt.Print("\n")
    break
  case "getDevice":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetDevice requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetDevice())
    fmt.Print("\n")
    break
  case "startServiceBroadcast":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "StartServiceBroadcast requires 1 args")
      flag.Usage()
    }
    tmp0, err80 := (strconv.Atoi(flag.Arg(1)))
    if err80 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.StartServiceBroadcast(value0))
    fmt.Print("\n")
    break
  case "stopServiceBroadcast":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "StopServiceBroadcast requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.StopServiceBroadcast())
    fmt.Print("\n")
    break
  case "deviceDiscovery":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "DeviceDiscovery requires 1 args")
      flag.Usage()
    }
    tmp0, err81 := (strconv.Atoi(flag.Arg(1)))
    if err81 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.DeviceDiscovery(value0))
    fmt.Print("\n")
    break
  case "searchForDevice":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "SearchForDevice requires 2 args")
      flag.Usage()
    }
    tmp0, err82 := (strconv.Atoi(flag.Arg(1)))
    if err82 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.SearchForDevice(value0, value1))
    fmt.Print("\n")
    break
  case "requestServices":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "RequestServices requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.RequestServices())
    fmt.Print("\n")
    break
  case "getServicePrices":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetServicePrices requires 1 args")
      flag.Usage()
    }
    tmp0, err84 := (strconv.Atoi(flag.Arg(1)))
    if err84 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    fmt.Print(client.GetServicePrices(value0))
    fmt.Print("\n")
    break
  case "selectService":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "SelectService requires 3 args")
      flag.Usage()
    }
    tmp0, err85 := (strconv.Atoi(flag.Arg(1)))
    if err85 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    tmp1, err86 := (strconv.Atoi(flag.Arg(2)))
    if err86 != nil {
      Usage()
      return
    }
    argvalue1 := int32(tmp1)
    value1 := argvalue1
    tmp2, err87 := (strconv.Atoi(flag.Arg(3)))
    if err87 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.SelectService(value0, value1, value2))
    fmt.Print("\n")
    break
  case "makePayment":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "MakePayment requires 1 args")
      flag.Usage()
    }
    arg88 := flag.Arg(1)
    mbTrans89 := thrift.NewTMemoryBufferLen(len(arg88))
    defer mbTrans89.Close()
    _, err90 := mbTrans89.WriteString(arg88)
    if err90 != nil {
      Usage()
      return
    }
    factory91 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt92 := factory91.GetProtocol(mbTrans89)
    argvalue0 := wpthrift_types.NewTotalPriceResponse()
    err93 := argvalue0.Read(jsProt92)
    if err93 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.MakePayment(value0))
    fmt.Print("\n")
    break
  case "beginServiceDelivery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "BeginServiceDelivery requires 3 args")
      flag.Usage()
    }
    tmp0, err94 := (strconv.Atoi(flag.Arg(1)))
    if err94 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    arg95 := flag.Arg(2)
    mbTrans96 := thrift.NewTMemoryBufferLen(len(arg95))
    defer mbTrans96.Close()
    _, err97 := mbTrans96.WriteString(arg95)
    if err97 != nil {
      Usage()
      return
    }
    factory98 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt99 := factory98.GetProtocol(mbTrans96)
    argvalue1 := wpthrift_types.NewServiceDeliveryToken()
    err100 := argvalue1.Read(jsProt99)
    if err100 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err101 := (strconv.Atoi(flag.Arg(3)))
    if err101 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.BeginServiceDelivery(value0, value1, value2))
    fmt.Print("\n")
    break
  case "endServiceDelivery":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "EndServiceDelivery requires 3 args")
      flag.Usage()
    }
    tmp0, err102 := (strconv.Atoi(flag.Arg(1)))
    if err102 != nil {
      Usage()
      return
    }
    argvalue0 := int32(tmp0)
    value0 := argvalue0
    arg103 := flag.Arg(2)
    mbTrans104 := thrift.NewTMemoryBufferLen(len(arg103))
    defer mbTrans104.Close()
    _, err105 := mbTrans104.WriteString(arg103)
    if err105 != nil {
      Usage()
      return
    }
    factory106 := thrift.NewTSimpleJSONProtocolFactory()
    jsProt107 := factory106.GetProtocol(mbTrans104)
    argvalue1 := wpthrift_types.NewServiceDeliveryToken()
    err108 := argvalue1.Read(jsProt107)
    if err108 != nil {
      Usage()
      return
    }
    value1 := argvalue1
    tmp2, err109 := (strconv.Atoi(flag.Arg(3)))
    if err109 != nil {
      Usage()
      return
    }
    argvalue2 := int32(tmp2)
    value2 := argvalue2
    fmt.Print(client.EndServiceDelivery(value0, value1, value2))
    fmt.Print("\n")
    break
  case "CloseRPCAgent":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "CloseRPCAgent requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.CloseRPCAgent())
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
